### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#10]
- [x]  create a components folder and inside a shared folder (if not existing)
- [x] create a footer component based on the figma file

**Comment by ReallyBoard123** [comment]
Update: 9/8 post lunch

**Comment by Hottinho** [comment]
Had some trouble reverse merging the main b/c of conflicts in the root layout now (new MainHeader). So vertical layout is a bit broken again and fotter not sticking to bottom.
