### ISSUE TITLE
Screen Design

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#3]
- [x] setup color palette
- [x] setup fonts (font types, weights...)
- [x] find an eye candy background
- [x] turn wireframes into high fidelity mockups

**Comment by ReallyBoard123** [comment]
- Background is now just plain black for the dashboard and form page. In the meanwhile whenever the team comes up with a solution - we will then vote on it and upgrade it for these pages.
