### ISSUE TITLE
create Job

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#35]
- [x] add create job buttons to the kanbanboard
- [x] link to the create job page (dont forget query param)
- [x] read out query param and prefill current stage
- [x] write a mutation for creating a job (react query)
- [x] write an api folder if not existing
- [x] create post request handler for creating a job
- [x] implement logic for creating a job (hint: dont forget to tie the job to an existing user)
- [x] implement success and error handling for mutation (Tipp you can use Toastify)

hint: you can use a searchparam for identify the column

wait till is done #34  #36

**Comment by pswu11** [comment]
Hi @RealBirdMan91  
since column id is required when creating a job, should this be depending on #36 as well?

**Comment by RealBirdMan91** [comment]
@pswu11  good point should be the case
