### ISSUE TITLE
create column

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#36]
- [x] Clicking on the plus button at Kanban board shoud create a new column
- [x] Column title should have a focused input field and a check icon on the right to submit the title value
- [x] make sure that the colours repeat in order
- [x] check that is not allowed that title could be empty
- [x] After submiting the title by Clicking the icon or hitting enter. The column should be saved in db (creating an api handler for that)
- [x] implement success and error handling (hint: you can use toastify therefor)

make sure that #34 is finished

**Comment by pswu11** [comment]
- when user is logged in, always look up columns using userId, if return is null, then generate templated columns for this user.
