### ISSUE TITLE
Board component - creating and deleting columns buggy

### ISSUE THREAD

**Issue by Hottinho** [devhausleipzigacademy/camp10-finalProject#59]
I noticed when you create a new column and later delete one or more, more than just the deleted columns disappear from the Kanban board. Sometimes also a column other than the created one disappear.

In parts this seems to be a visual/rendering problem because after a manual refresh or the browser the deleted column is gone and the others who were not deleted re-appear again.
Since I have deleted all standard columns and created a bunch of new ones for my user, I'm not sure of the exact steps for reproduction, but it seems to have to do with the color assigned to the newly created column.

1. Add a column with the + Button
2. Give it a name of your liking.
3. Add another column and name it.

Expected behaviour: New column will be added.
Shown behaviour (if new column has same color as other new column): New column will be added but other column disappears.

4. Reload - columns are now both there.
5. Delete the column you first added.

Expected behaviour: Column will be deleted.
Shown behaviour: All user created columns with same color will disappear, too.

6. Reload

**Comment by pswu11** [comment]
One confirmed bug - when deleting a column that has a card inside, it will fail. 

Potential solutions are: 
- It shouldn't be allowed - prompt a reminder and do nothing => this will be a very quick fix. 
- It should prompt a popup to the user and ask for confirmation - that this will delete the column and delete ALL the jobs inside. => this can be added later as an improvement.

**Comment by Hottinho** [comment]
There seems to be a problem with a position being assigned twice (see "positioninBoard" in prisma studio
screenshot)

![grafik](https://github.com/devhausleipzigacademy/camp10-finalProject/assets/10983364/901d3fb7-1ea2-4803-84bf-ca311765b3cf)
