### ISSUE TITLE
Kanban board Card

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#71]
- [x] cards should be able to moved collapsed as well as extended (https://react-icons.github.io/react-icons/search?q=expand)
- [x] whole card should be collapsable on an arrow down
- [x] clicking on three dots opens dropdown menu
- [x] menu points should be delete, edit and view
- [x] delete function should delete a card
- [x] view should lead to view page
- [x] edit should lead to edit page

**Comment by systm-spec** [comment]
View & Edit placeholder until view/edit ready.
delete tested
DropDown-Refactor needed.
