### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by RealBirdMan91** [devhausleipzigacademy/camp10-finalProject#8]
- [x] create a components folder and inside a shared folder (if not existing)
- [x] create a button Component based on the Screendesign
- [ ] Make sure you have sizes prop. Which accepts four strings. "small", "medium", "large", "fullwidth"

https://www.figma.com/file/kR8s6fHwwWIwpshpa5SKNt/design-system?type=design&node-id=1-786&mode=design&t=CdWgk4TQuJroBq7q-0

**Comment by ReallyBoard123** [comment]
Note: Standup 9/08 : Hendryk will update

**Comment by Hottinho** [comment]
The Buttons as of now seem to have "static" options like "hover" and "primary". However, these properties are for example triggered by mouse hovering and should probably not be defined when calling the component. I do need the button to turn red, when the mouse hovers over it, but I don't need a "hover" button which will always be red.
